name: Build C Project on Self-Hosted Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted  # Uses your VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile C code
        run: gcc -o my_program main.c

      - name: Run program
        run: ./my_program

